services:
  - type: web
    name: whatsapp-group-insights-analyzer
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn myproject.wsgi:application --access-logfile - --error-logfile - --log-level info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings_render
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

